apiVersion: v1
kind: ConfigMap
metadata:
  name: notesbhej-stage-config
  namespace: notesbhej-stage
data:
  SPRING_APPLICATION_NAME: notesbhej
  APP_ENV: stage
  APP_FRONTEND_URL: https://notesbhej-stage.mshiv.net
  SPRING_DATASOURCE_URL: jdbc:postgresql://10.0.1.20:5432/spring_app_stage
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: openid,profile,email
  SPRING_DEVTOOLS_RESTART_ENABLED: "false"
  SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "false"
  SERVER_MAX_HTTP_REQUEST_HEADER_SIZE: "32768"
  SERVER_FORWARD_HEADERS_STRATEGY: framework
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_METRICS_TAGS_APPLICATION: notesbhej-stage
  APP_USE_DEV: "false"
  APP_BUCKET: notes-stage
  APP_PUBLIC_URL: https://stage-data.mshiv.net
  MINIO_ENDPOINT: http://host.docker.internal:9000
  R2_ENDPOINT: https://8125c1d09c1a52e66574d7ccdec40a3c.r2.cloudflarestorage.com
