apiVersion: v1
kind: Service
metadata:
  name: notesbhej-api-stage
  namespace: notesbhej-stage
  labels:
    app.kubernetes.io/name: notesbhej-api-stage
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: notesbhej-api-stage
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30008
